import * as Phaser from '/node_modules/phaser/dist/phaser.esm.js';

const $=s=>document.querySelector(s), menu=$('#menu'),panel=$('#panel'),game=$('#game'),canvas=$('#world'),ctx=canvas.getContext('2d');
let socket=null,reconnectTimer=0,room=null,state=null,myId=null,lang=localStorage.getItem('tidelands.lang')||'en',camera={x:0,y:0,zoom:1},drag=null,hover=null;
const T={en:{create:'CREATE ROOM',rooms:'ROOMS',how:'HOW TO PLAY',settings:'SETTINGS',name:'Player Name',room:'Room Name',max:'Max Players',private:'Private room',createNow:'CREATE',join:'JOIN',back:'BACK',refresh:'REFRESH',ready:'READY',start:'START MATCH',players:'PLAYERS',objective:'OBJECTIVE',credits:'Credits',materials:'Materials',energy:'Energy',population:'Population',industry:'Industry',claim:'CLAIM TILE • 300',building:'BUILD',noServer:'Server unavailable — start the Render/Node server.'},fa:{create:'ساخت روم',rooms:'روم‌ها',how:'نحوه بازی',settings:'تنظیمات',name:'نام بازیکن',room:'نام روم',max:'حداکثر بازیکن',private:'روم خصوصی',createNow:'ساخت',join:'ورود',back:'بازگشت',refresh:'بروزرسانی',ready:'آماده',start:'شروع بازی',players:'بازیکنان',objective:'هدف',credits:'اعتبار',materials:'مواد',energy:'انرژی',population:'جمعیت',industry:'صنعت',claim:'تصرف خانه • ۳۰۰',building:'ساختمان',noServer:'سرور در دسترس نیست — ابتدا سرور Render/Node را اجرا کن.'}};
const tr=k=>T[lang][k]||k;
function send(m){if(socket?.readyState===1)socket.send(JSON.stringify(m))}
function connect(){if(socket&&socket.readyState<2)return;const proto=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${proto}://${location.host}`);$('#connection').textContent='CONNECTING…';socket.onopen=()=>{$('#connection').textContent='ONLINE';send({type:'list_rooms'})};socket.onclose=()=>{$('#connection').textContent='RECONNECTING…';clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,1500)};socket.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}handle(m)}}
function handle(m){if(m.type==='room_created'||m.type==='joined'){room=m.room;myId=room.players.find(p=>p.name===localStorage.getItem('tidelands.name'))?.id||myId;showRoom()}if(m.type==='room_update'){room=m.room;if(panel.classList.contains('hidden')===false)showRoom(true)}if(m.type==='rooms')renderRooms(m.rooms);if(m.type==='match_started'){state=m.state;room=m.state.room;myId=room.players.find(p=>p.name===localStorage.getItem('tidelands.name'))?.id||myId;enterGame()}if(m.type==='state'){state=m;room=m.room;enterGame()}if(m.type==='state_delta'){applyDelta(m)}if(m.type==='tick'){if(state){state.tick=m.tick;for(const p of m.players){const s=state.match.players.find(x=>x.id===p.id);if(s)Object.assign(s,p)}}render()}if(m.type==='chat'){addChat(`<b>${esc(m.from)}</b>: ${esc(m.text)}`)}if(m.type==='error'){toast(m.code)}}
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function openPanel(html){panel.innerHTML=`<div class="card">${html}</div>`;panel.classList.remove('hidden')}
function closePanel(){panel.classList.add('hidden');panel.innerHTML=''}
function showRoom(update=false){const p=room.players;openPanel(`<h2>${esc(room.name)}</h2><p class="muted">Room ID: <b>${room.id}</b> • ${p.length}/${room.maxPlayers}</p><div id="roomPlayers">${p.map(x=>`<div class="room"><span>${esc(x.name)} <small>${x.team||''}</small></span><span class="${x.ready?'good':'warn'}">${x.ready?'READY':'WAITING'}</span></div>`).join('')}</div><div class="row"><button class="action" id="ready">${tr('ready')}</button><button class="action" id="start">${tr('start')}</button><button class="action" id="leave">${tr('back')}</button></div>`);$('#ready').onclick=()=>send({type:'ready',ready:true});$('#start').onclick=()=>send({type:'start'});$('#leave').onclick=()=>{send({type:'leave'});room=null;closePanel()}}
function createUI(){openPanel(`<h2>${tr('create')}</h2><div class="field"><label>${tr('name')}</label><input id="pname" value="${esc(localStorage.getItem('tidelands.name')||'Player')}" maxlength="18"></div><div class="field"><label>${tr('room')}</label><input id="rname" value="TIDELANDS ROOM" maxlength="28"></div><div class="field"><label>${tr('max')}</label><select id="max"><option>2</option><option>4</option><option>8</option><option>16</option><option>32</option></select></div><label><input id="priv" type="checkbox"> ${tr('private')}</label><div class="row" style="margin-top:16px"><button class="action" id="make">${tr('createNow')}</button><button class="back" id="cancel">${tr('back')}</button></div>`);$('#make').onclick=()=>{const n=$('#pname').value.trim();localStorage.setItem('tidelands.name',n);send({type:'create_room',playerName:n,name:$('#rname').value,maxPlayers:+$('#max').value,private:$('#priv').checked})};$('#cancel').onclick=closePanel}
function roomsUI(){openPanel(`<h2>${tr('rooms')}</h2><div id="roomList">Loading…</div><div class="row"><button class="action" id="refresh">${tr('refresh')}</button><button class="back" id="back">${tr('back')}</button></div>`);$('#refresh').onclick=()=>send({type:'list_rooms'});$('#back').onclick=closePanel;send({type:'list_rooms'})}
function renderRooms(rs){const el=$('#roomList');if(!el)return;el.innerHTML=rs.length?rs.map(r=>`<div class="room"><div><b>${esc(r.name)}</b><br><small>${r.players.length}/${r.maxPlayers} • ${r.id}</small></div><button class="action" data-id="${r.id}">${tr('join')}</button></div>`).join(''):'<p>No public rooms yet.</p>';el.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const n=prompt(tr('name'),localStorage.getItem('tidelands.name')||'Player')||'Player';localStorage.setItem('tidelands.name',n);send({type:'join_room',roomId:b.dataset.id,playerName:n})})}
function howUI(){openPanel(`<h2>${tr('how')}</h2><p>Build cities, connect infrastructure, grow your economy, explore the fog of war and negotiate with other players. Claim adjacent land, place buildings, and complete the shared match objective.</p><ul><li>Desktop: drag map • click tiles • build bar</li><li>Mobile: drag to pan • tap tiles • horizontal build bar</li><li>Server validates important actions; the browser never owns the authoritative match state.</li><li>Disconnects trigger automatic reconnect and resync.</li></ul><button class="back" id="back">${tr('back')}</button>`);$('#back').onclick=closePanel}
function settingsUI(){openPanel(`<h2>${tr('settings')}</h2><div class="field"><label>Graphics</label><select><option>High</option><option>Medium</option><option>Low</option></select></div><div class="field"><label>Master Volume</label><input type="range" min="0" max="100" value="70"></div><button class="back" id="back">${tr('back')}</button>`);$('#back').onclick=closePanel}
function bindMenu(){document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>({create:createUI,rooms:roomsUI,how:howUI,settings:settingsUI}[b.dataset.screen])());$('#langBtn').onclick=()=>{lang=lang==='en'?'fa':'en';localStorage.setItem('tidelands.lang',lang);location.reload()}}
function enterGame(){closePanel();menu.classList.add('hidden');game.classList.remove('hidden');resize();buildBar();render();}
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);}
function worldToScreen(x,y){return [(x-camera.x)*camera.zoom+innerWidth/2,(y-camera.y)*camera.zoom+innerHeight/2]}
function screenToWorld(x,y){return [(x-innerWidth/2)/camera.zoom+camera.x,(y-innerHeight/2)/camera.zoom+camera.y]}
function tileAt(sx,sy){if(!state?.match)return null;const [wx,wy]=screenToWorld(sx,sy);const size=34;const x=Math.floor(wx/size),y=Math.floor(wy/size);if(x<0||y<0||x>=state.match.map.w||y>=state.match.map.h)return null;return state.match.map.tiles[y*state.match.map.w+x]}
const terr={water:'#08769c',land:'#5b9f53',forest:'#367343',mountain:'#6f756e',dry:'#ad9a55',snow:'#cfe7e8',volcanic:'#6d473d',beach:'#d8c47a'};
function render(){if(game.classList.contains('hidden'))return;const W=innerWidth,H=innerHeight;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,W,H);ctx.fillStyle='#075a78';ctx.fillRect(0,0,W,H);const m=state?.match?.map;if(!m)return;const size=34;for(const t of m.tiles){const [sx,sy]=worldToScreen(t.x*size+size/2,t.y*size+size/2);const s=size*camera.zoom+1;if(sx<-s||sy<-s||sx>W+s||sy>H+s)continue;ctx.fillStyle=terr[t.terrain];ctx.fillRect(sx-s/2,sy-s/2,s,s);ctx.globalAlpha=.16;ctx.fillStyle='#fff';if(t.terrain==='forest'){for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(sx-s*.25+i*s*.2,sy,Math.max(2,s*.11),0,7);ctx.fill()}}if(t.terrain==='mountain'){ctx.beginPath();ctx.moveTo(sx-s*.3,sy+s*.25);ctx.lineTo(sx,sy-s*.3);ctx.lineTo(sx+s*.3,sy+s*.25);ctx.fill()}ctx.globalAlpha=1;if(t.resource){ctx.fillStyle='#f6d35e';ctx.beginPath();ctx.arc(sx,sy,s*.12,0,7);ctx.fill()}if(t.owner){ctx.fillStyle=ownerColor(t.owner);ctx.globalAlpha=.23;ctx.fillRect(sx-s/2,sy-s/2,s,s);ctx.globalAlpha=1}if(t.city){ctx.fillStyle='#e9eef3';ctx.fillRect(sx-9,sy-8,18,16);ctx.fillStyle='#27465c';ctx.fillRect(sx-6,sy-13,12,6);ctx.fillStyle='#e4b74b';ctx.fillRect(sx-2,sy-5,4,8)} }
 drawRoads(m,size); drawPlayers(); drawHud(); }
function ownerColor(id){const p=state.match.players.find(x=>x.id===id);return p?.team==='Red'?'#ef5964':p?.team==='Green'?'#61db82':'#50bfff'}
function drawRoads(m,size){ctx.strokeStyle='#d5c89b99';ctx.lineWidth=2;for(const t of m.tiles)if(t.city){const [sx,sy]=worldToScreen(t.x*size+size/2,t.y*size+size/2);ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx+size*camera.zoom,sy);ctx.stroke()}}
function drawPlayers(){if(!state?.match)return;for(const p of state.match.players){const [sx,sy]=worldToScreen(p.x*34+17,p.y*34+17);ctx.fillStyle=ownerColor(p.id);ctx.beginPath();ctx.arc(sx,sy,8,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText(p.name,sx,sy-13)}}
function drawHud(){const my=state.match.players.find(p=>p.id===myId)||state.match.players[0];const r=my?.resources||{};$('#hud').innerHTML=`<div class="hud"><div class="hudPanel"><div class="brandSmall">◈ TIDELANDS</div></div><div class="hudPanel res"><span>🪙 <b>${fmt(r.credits)}</b></span><span>🧱 <b>${fmt(r.materials)}</b></span><span>⚡ <b>${fmt(r.energy)}</b></span><span>👥 <b>${fmt(r.population)}</b></span><span>⚙ <b>${fmt(r.industry)}</b></span></div><div class="hudPanel">Tick ${state.tick||0}</div></div><div class="side"><button>${tr('building')}</button><button>${tr('objective')}</button><button>Diplomacy</button><button>Map</button></div><div class="right"><div class="hudPanel objective"><b>${tr('objective')}</b><div>${esc(state.match.objective.name)}</div><small>${esc(state.match.objective.desc)}</small><div class="meter"><i style="width:${my?.objectiveProgress||0}%"></i></div></div></div>`}
function fmt(n){return Math.floor(n||0).toLocaleString()}
function buildBar(){const names=[['city','City Center'],['farm','Farm'],['mine','Mine'],['factory','Factory'],['power','Power Plant'],['warehouse','Warehouse'],['port','Port'],['airport','Airport'],['radar','Radar'],['defense','Defense']];$('#buildbar').innerHTML=names.map(([id,n])=>`<button class="build" data-build="${id}">${n}<span>BUILD</span></button>`).join('');$('#buildbar').querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{if(hover)send({type:'build',building:b.dataset.build,x:hover.x,y:hover.y})})}
function applyDelta(m){if(!state?.match)return;const p=state.match.players.find(x=>x.id===m.playerId);if(p&&m.resources)p.resources=m.resources;const a=m.action;if(a?.type==='tile_claimed'){const t=state.match.map.tiles.find(t=>t.x===a.x&&t.y===a.y);if(t)t.owner=m.playerId}if(a?.type==='building_added')p?.buildings?.push(a.building);render()}
function addChat(s){const el=$('#chatLog');if(!el)return;el.innerHTML+=`<div>${s}</div>`;el.scrollTop=el.scrollHeight}
function toast(s){addChat(`<span class="bad">${esc(s)}</span>`)}
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag){camera.x=drag.cx-(e.clientX-drag.x)/camera.zoom;camera.y=drag.cy-(e.clientY-drag.y)/camera.zoom;render()}hover=tileAt(e.clientX,e.clientY)});canvas.addEventListener('pointerup',e=>{if(!drag)return;const moved=Math.hypot(e.clientX-drag.x,e.clientY-drag.y);if(moved<6){hover=tileAt(e.clientX,e.clientY);if(hover&&hover.terrain!=='water'){if(hover.owner===null)send({type:'claim',x:hover.x,y:hover.y});}}drag=null});canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=Math.max(.55,Math.min(1.8,camera.zoom*(e.deltaY<0?1.08:.93)));render()},{passive:false});addEventListener('resize',()=>{resize();render()});$('#chat form').onsubmit=e=>{e.preventDefault();const v=$('#chatInput').value.trim();if(v)send({type:'chat',text:v});$('#chatInput').value=''};
bindMenu();connect();
// Phaser is intentionally loaded so the client remains Phaser-ready for future scene expansion; the current renderer uses a lightweight canvas layer for maximum mobile performance.
void Phaser;
