import * as Phaser from '/node_modules/phaser/dist/phaser.esm.js';

const $=s=>document.querySelector(s), menu=$('#menu'),panel=$('#panel'),game=$('#game'),canvas=$('#world'),ctx=canvas.getContext('2d');
let socket=null,reconnectTimer=0,room=null,state=null,myId=null,lang=localStorage.getItem('tidelands.lang')||'en';
let camera={x:700,y:460,zoom:1},drag=null,hover=null,selected=null,buildMode=null,lastPointer={x:0,y:0};
const TILE=38;
const T={en:{create:'CREATE ROOM',rooms:'ROOMS',how:'HOW TO PLAY',settings:'SETTINGS',name:'Player Name',room:'Room Name',max:'Max Players',private:'Private room',createNow:'CREATE',join:'JOIN',back:'BACK',refresh:'REFRESH',ready:'READY',start:'START MATCH',players:'PLAYERS',objective:'OBJECTIVE',credits:'Credits',materials:'Materials',energy:'Energy',population:'Population',industry:'Industry',claim:'CLAIM LAND • 300',build:'BUILD',cancel:'CANCEL BUILD',select:'SELECTED',connected:'ONLINE',connecting:'CONNECTING…',reconnecting:'RECONNECTING…',message:'Message…',noServer:'Server unavailable — start the Render/Node server.'},fa:{create:'ساخت روم',rooms:'روم‌ها',how:'نحوه بازی',settings:'تنظیمات',name:'نام بازیکن',room:'نام روم',max:'حداکثر بازیکن',private:'روم خصوصی',createNow:'ساخت',join:'ورود',back:'بازگشت',refresh:'بروزرسانی',ready:'آماده',start:'شروع بازی',players:'بازیکنان',objective:'هدف',credits:'اعتبار',materials:'مواد',energy:'انرژی',population:'جمعیت',industry:'صنعت',claim:'تصرف زمین • ۳۰۰',build:'ساخت',cancel:'لغو ساخت',select:'انتخاب',connected:'آنلاین',connecting:'در حال اتصال…',reconnecting:'اتصال مجدد…',message:'پیام…',noServer:'سرور در دسترس نیست — ابتدا سرور Render/Node را اجرا کن.'}};
const tr=k=>T[lang][k]||k;
function send(m){if(socket?.readyState===1)socket.send(JSON.stringify(m))}
function connect(){if(socket&&socket.readyState<2)return;const proto=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${proto}://${location.host}`);setConnection(tr('connecting'));socket.onopen=()=>{setConnection(tr('connected'));const saved=JSON.parse(localStorage.getItem('tidelands.session')||'null');if(saved?.roomId&&saved?.playerId&&saved?.reconnectToken)send({type:'reconnect',...saved});else send({type:'list_rooms'});};socket.onclose=()=>{setConnection(tr('reconnecting'));clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,1500)};socket.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}handle(m)}}
function setConnection(v){const el=$('#connection');if(el)el.textContent=v}
function handle(m){
 if(m.type==='room_created'||m.type==='joined'){room=m.room;if(m.playerId)myId=m.playerId;if(m.reconnectToken)localStorage.setItem('tidelands.session',JSON.stringify({roomId:room.id,playerId:myId,reconnectToken:m.reconnectToken}));showRoom()}
 if(m.type==='room_update'){room=m.room;if(panel.classList.contains('hidden')===false)showRoom(true)}
 if(m.type==='rooms')renderRooms(m.rooms)
 if(m.type==='match_started'){state=m.state;room=m.state.room;if(m.playerId)myId=m.playerId;myId=myId||room.players.find(p=>p.name===localStorage.getItem('tidelands.name'))?.id;enterGame()}
 if(m.type==='state'){state=m;room=m.room;if(m.playerId)myId=m.playerId;if(m.reconnectToken)localStorage.setItem('tidelands.session',JSON.stringify({roomId:room.id,playerId:myId,reconnectToken:m.reconnectToken}));enterGame()}
 if(m.type==='state_delta'){applyDelta(m)}
 if(m.type==='tick'){if(state){state.tick=m.tick;for(const p of m.players){const s=state.match.players.find(x=>x.id===p.id);if(s)Object.assign(s,p)}render()}}
 if(m.type==='chat')addChat(`<b>${esc(m.from)}</b>: ${esc(m.text)}`)
 if(m.type==='error'){toast(m.code);if(m.code==='RECONNECT_FAILED')localStorage.removeItem('tidelands.session')}
}
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
function openPanel(html){panel.innerHTML=`<div class="card">${html}</div>`;panel.classList.remove('hidden')}
function closePanel(){panel.classList.add('hidden');panel.innerHTML=''}
function showRoom(){const p=room.players;openPanel(`<div class="roomTop"><div><div class="eyebrow">TIDELANDS • ROOM</div><h2>${esc(room.name)}</h2><p class="muted">ID <b>${room.id}</b> • ${p.length}/${room.maxPlayers}</p></div><button class="iconBtn" id="copyRoom">⧉</button></div><div id="roomPlayers">${p.map(x=>`<div class="room"><span><b>${esc(x.name)}</b> <small>${x.team||''}</small></span><span class="${x.ready?'good':'warn'}">${x.connected?'':'OFFLINE • '}${x.ready?'READY':'WAITING'}</span></div>`).join('')}</div><div class="row roomActions"><button class="action" id="ready">${tr('ready')}</button><button class="action primary" id="start">${tr('start')}</button><button class="back" id="leave">${tr('back')}</button></div>`);$('#ready').onclick=()=>send({type:'ready',ready:true});$('#start').onclick=()=>send({type:'start'});$('#leave').onclick=()=>{send({type:'leave'});room=null;localStorage.removeItem('tidelands.session');closePanel()};$('#copyRoom').onclick=async()=>{try{await navigator.clipboard.writeText(room.id);toast('ROOM ID COPIED')}catch{toast(room.id)}}}
function createUI(){openPanel(`<h2>${tr('create')}</h2><div class="field"><label>${tr('name')}</label><input id="pname" value="${esc(localStorage.getItem('tidelands.name')||'Player')}" maxlength="18"></div><div class="field"><label>${tr('room')}</label><input id="rname" value="TIDELANDS ROOM" maxlength="28"></div><div class="field"><label>${tr('max')}</label><select id="max"><option>2</option><option>4</option><option>8</option><option>16</option><option>32</option></select></div><label class="check"><input id="priv" type="checkbox"> ${tr('private')}</label><div class="row" style="margin-top:16px"><button class="action primary" id="make">${tr('createNow')}</button><button class="back" id="cancel">${tr('back')}</button></div>`);$('#make').onclick=()=>{const n=$('#pname').value.trim()||'Player';localStorage.setItem('tidelands.name',n);send({type:'create_room',playerName:n,name:$('#rname').value.trim()||'TIDELANDS ROOM',maxPlayers:+$('#max').value,private:$('#priv').checked})};$('#cancel').onclick=closePanel}
function roomsUI(){openPanel(`<h2>${tr('rooms')}</h2><div id="roomList">Loading…</div><div class="row"><button class="action" id="refresh">${tr('refresh')}</button><button class="action" id="manualJoin">${tr('join')}</button><button class="back" id="back">${tr('back')}</button></div>`);$('#refresh').onclick=()=>send({type:'list_rooms'});$('#manualJoin').onclick=()=>{const id=prompt('ROOM ID');if(id){const n=prompt(tr('name'),localStorage.getItem('tidelands.name')||'Player')||'Player';localStorage.setItem('tidelands.name',n);send({type:'join_room',roomId:id,playerName:n})}};$('#back').onclick=closePanel;send({type:'list_rooms'})}
function renderRooms(rs){const el=$('#roomList');if(!el)return;el.innerHTML=rs.length?rs.map(r=>`<div class="room"><div><b>${esc(r.name)}</b><br><small>${r.players.length}/${r.maxPlayers} • ${r.id}</small></div><button class="action" data-id="${r.id}">${tr('join')}</button></div>`).join(''):'<p class="muted">No public rooms yet.</p>';el.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const n=prompt(tr('name'),localStorage.getItem('tidelands.name')||'Player')||'Player';localStorage.setItem('tidelands.name',n);send({type:'join_room',roomId:b.dataset.id,playerName:n})})}
function howUI(){openPanel(`<h2>${tr('how')}</h2><div class="helpGrid"><div><b>🗺 Map</b><p>Drag to move. Wheel or pinch to zoom. Tap a land tile to select it.</p></div><div><b>🏗 Build</b><p>Select one of the building cards at the bottom, then tap your territory.</p></div><div><b>💰 Economy</b><p>Buildings increase production. Expand adjacent land with 300 Credits.</p></div><div><b>🎯 Objective</b><p>Your match objective is shown on the right. The server validates every action.</p></div></div><button class="back" id="back">${tr('back')}</button>`);$('#back').onclick=closePanel}
function settingsUI(){openPanel(`<h2>${tr('settings')}</h2><div class="field"><label>Graphics</label><select id="quality"><option>High</option><option>Medium</option><option>Low</option></select></div><div class="field"><label>Master Volume</label><input type="range" min="0" max="100" value="70"></div><div class="field"><label>Language</label><button class="action" id="setLang">${lang==='en'?'فارسی':'ENGLISH'}</button></div><button class="back" id="back">${tr('back')}</button>`);$('#back').onclick=closePanel;$('#setLang').onclick=()=>{lang=lang==='en'?'fa':'en';localStorage.setItem('tidelands.lang',lang);location.reload()}}
function bindMenu(){document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>({create:createUI,rooms:roomsUI,how:howUI,settings:settingsUI}[b.dataset.screen])());$('#langBtn').onclick=()=>{lang=lang==='en'?'fa':'en';localStorage.setItem('tidelands.lang',lang);location.reload()}}
function enterGame(){closePanel();menu.classList.add('hidden');game.classList.remove('hidden');resize();camera.x=700;camera.y=470;buildBar();render()}
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}
function worldToScreen(x,y){return [(x-camera.x)*camera.zoom+innerWidth/2,(y-camera.y)*camera.zoom+innerHeight/2]}
function screenToWorld(x,y){return [(x-innerWidth/2)/camera.zoom+camera.x,(y-innerHeight/2)/camera.zoom+camera.y]}
function tileAt(sx,sy){if(!state?.match)return null;const [wx,wy]=screenToWorld(sx,sy);const x=Math.floor(wx/TILE),y=Math.floor(wy/TILE);if(x<0||y<0||x>=state.match.map.w||y>=state.match.map.h)return null;return state.match.map.tiles[y*state.match.map.w+x]}
const terr={water:'#167da0',land:'#67a653',forest:'#438449',mountain:'#a9a99d',dry:'#b59d61',snow:'#dbe6e5',volcanic:'#735049',beach:'#e5cb87'};
const teams={Blue:'#2e9cf5',Red:'#ef4f56',Green:'#48d66f',Purple:'#a16cff',Yellow:'#f3c84b',Pink:'#ef74bd'};
function hash(x,y){let n=(x*374761393+y*668265263)>>>0;n=(n^(n>>13))*1274126177>>>0;return (n^(n>>16))>>>0}
function render(){if(game.classList.contains('hidden'))return;const d=Math.min(devicePixelRatio||1,2);ctx.setTransform(d,0,0,d,0,0);const W=innerWidth,H=innerHeight;ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#07556f');g.addColorStop(.5,'#0b7691');g.addColorStop(1,'#06485f');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);const m=state?.match?.map;if(!m)return;
 for(const t of m.tiles)drawTile(t,m);
 drawWaterDetails(m);drawRoads(m);drawEntities(m);drawSelection();drawHud();
}
function drawTile(t,m){const [sx,sy]=worldToScreen(t.x*TILE,t.y*TILE),s=TILE*camera.zoom+1;if(sx<-s||sy<-s||sx>innerWidth+s||sy>innerHeight+s)return;ctx.fillStyle=terr[t.terrain];ctx.fillRect(sx,sy,s,s);ctx.globalAlpha=.18;ctx.fillStyle=t.terrain==='water'?'#b9f2ff':'#fff';ctx.fillRect(sx,sy,s,1);ctx.globalAlpha=1;
 const h=hash(t.x,t.y), z=Math.max(.55,camera.zoom);
 if(['land','forest','dry','snow','volcanic','beach'].includes(t.terrain)){ctx.save();ctx.translate(sx,sy);for(let i=0;i<(t.terrain==='forest'?4:2);i++){const ox=((h>>(i*3))%26+5)*z,oy=((h>>(i*5+2))%25+5)*z;if(t.terrain==='forest'){ctx.fillStyle='#245d37';ctx.beginPath();ctx.arc(ox,oy,5*z,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4f9650';ctx.beginPath();ctx.arc(ox-2*z,oy-3*z,4*z,0,Math.PI*2);ctx.fill()}else if(t.terrain==='mountain'){ }else {ctx.fillStyle=t.terrain==='snow'?'#a5c7c5':t.terrain==='dry'?'#8e7743':'#4b8b4b';ctx.fillRect(ox,oy,2*z,5*z)}}ctx.restore()}
 if(t.terrain==='mountain'){ctx.fillStyle='#72766f';ctx.beginPath();ctx.moveTo(sx+7*z,sy+30*z);ctx.lineTo(sx+19*z,sy+6*z);ctx.lineTo(sx+31*z,sy+30*z);ctx.closePath();ctx.fill();ctx.fillStyle='#eef2ed';ctx.beginPath();ctx.moveTo(sx+14*z,sy+16*z);ctx.lineTo(sx+19*z,sy+6*z);ctx.lineTo(sx+24*z,sy+17*z);ctx.closePath();ctx.fill()}
 if(t.terrain==='volcanic'){ctx.fillStyle='#3d2824';ctx.beginPath();ctx.moveTo(sx+4*z,sy+34*z);ctx.lineTo(sx+19*z,sy+7*z);ctx.lineTo(sx+34*z,sy+34*z);ctx.fill();ctx.fillStyle='#f07b2c';ctx.beginPath();ctx.moveTo(sx+19*z,sy+9*z);ctx.lineTo(sx+16*z,sy+27*z);ctx.lineTo(sx+20*z,sy+31*z);ctx.lineTo(sx+23*z,sy+25*z);ctx.fill()}
 if(t.resource){ctx.fillStyle='#ffd45d';ctx.beginPath();ctx.arc(sx+28*z,sy+9*z,3.5*z,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff1a0';ctx.stroke()}
 if(t.owner){ctx.fillStyle=teams[state.match.players.find(p=>p.id===t.owner)?.team]||'#4cbcff';ctx.globalAlpha=.16;ctx.fillRect(sx,sy,s,s);ctx.globalAlpha=1;ctx.strokeStyle=teams[state.match.players.find(p=>p.id===t.owner)?.team]||'#4cbcff';ctx.globalAlpha=.34;ctx.strokeRect(sx+1,sy+1,s-2,s-2);ctx.globalAlpha=1}
 if(t.city)drawCity(t,sx,sy,z);if(t.owner){const owner=state.match.players.find(p=>p.id===t.owner);const list=owner?.buildings||[];const b=list.find(q=>q.x===t.x&&q.y===t.y);if(b&&!t.city)drawBuilding(b,sx,sy,z)}
}

function drawBuilding(b,sx,sy,z){ctx.save();ctx.translate(sx+19*z,sy+20*z);ctx.fillStyle='#c9d5dc';ctx.strokeStyle='#28475a';ctx.lineWidth=1;ctx.shadowBlur=7*z;ctx.shadowColor='#9deaff55';ctx.fillRect(-9*z,-7*z,18*z,13*z);ctx.strokeRect(-9*z,-7*z,18*z,13*z);ctx.fillStyle='#7ca6b8';ctx.fillRect(-6*z,-12*z,12*z,6*z);ctx.fillStyle='#f2c65b';ctx.fillRect(-2*z,1*z,4*z,5*z);ctx.fillStyle='#5bdcff';ctx.globalAlpha=.75;ctx.fillRect(-9*z,-7*z,3*z,13*z);ctx.restore()}
function drawCity(t,sx,sy,z){const team=state.match.players.find(p=>p.id===t.owner)?.team||'Blue';ctx.save();ctx.translate(sx+19*z,sy+20*z);ctx.shadowBlur=10*z;ctx.shadowColor=teams[team];ctx.fillStyle='#dce6ed';ctx.fillRect(-12*z,-6*z,24*z,14*z);ctx.fillStyle='#9eb4c4';ctx.fillRect(-9*z,-14*z,7*z,22*z);ctx.fillRect(2*z,-20*z,7*z,28*z);ctx.fillStyle='#35556b';ctx.fillRect(-7*z,-11*z,3*z,4*z);ctx.fillRect(4*z,-16*z,3*z,4*z);ctx.fillStyle='#e9bd50';ctx.fillRect(0,1*z,4*z,7*z);ctx.restore();
 const name=t.city.name||'City';ctx.font=`700 ${Math.max(10,12*z)}px system-ui`;const tw=ctx.measureText(name).width+46;ctx.fillStyle='#061522e8';roundRect(sx+19*z-tw/2,sy-15*z,tw,22*z,6*z);ctx.fill();ctx.fillStyle=teams[team];ctx.fillRect(sx+19*z-tw/2,sy-15*z,6*z,22*z);ctx.fillStyle='#fff';ctx.textAlign='left';ctx.fillText(name,sx+19*z-tw/2+12*z,sy+1*z);ctx.fillStyle='#fff';ctx.font=`700 ${Math.max(9,10*z)}px system-ui`;ctx.textAlign='right';ctx.fillText(String(t.city.level||1),sx+19*z+tw/2-8*z,sy+1*z);ctx.textAlign='center'}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawWaterDetails(m){ctx.save();ctx.globalAlpha=.28;ctx.strokeStyle='#8eeaff';ctx.lineWidth=1;for(let y=1;y<m.h;y+=3){for(let x=1;x<m.w;x+=4){const t=m.tiles[y*m.w+x];if(t?.terrain==='water'){const [sx,sy]=worldToScreen(x*TILE+7,y*TILE+26);ctx.beginPath();ctx.moveTo(sx,sy);ctx.quadraticCurveTo(sx+8*camera.zoom,sy-2*camera.zoom,sx+16*camera.zoom,sy);ctx.stroke()}}}ctx.restore()}
function drawRoads(m){ctx.save();ctx.lineCap='round';for(const t of m.tiles){if(!t.city)continue;const [sx,sy]=worldToScreen(t.x*TILE+19,t.y*TILE+25);ctx.strokeStyle='#d9d1ae';ctx.lineWidth=5*camera.zoom;ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx+60*camera.zoom,sy);ctx.stroke();ctx.strokeStyle='#8c8a75';ctx.lineWidth=1.5*camera.zoom;ctx.stroke()}ctx.restore()}
function drawEntities(m){for(const p of state.match.players){const [sx,sy]=worldToScreen(p.x*TILE+19,p.y*TILE+19);ctx.save();ctx.fillStyle=teams[p.team]||'#fff';ctx.shadowBlur=12;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(sx,sy,7*camera.zoom,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(sx,sy-1,2.2*camera.zoom,0,Math.PI*2);ctx.fill();ctx.font=`700 ${Math.max(9,11*camera.zoom)}px system-ui`;ctx.textAlign='center';ctx.fillText(p.name,sx,sy-13*camera.zoom);ctx.restore()}}
function drawSelection(){if(!hover)return;const [sx,sy]=worldToScreen(hover.x*TILE,hover.y*TILE),s=TILE*camera.zoom;ctx.save();ctx.strokeStyle=buildMode?'#ffd35a':'#8eeaff';ctx.lineWidth=2;ctx.setLineDash([5,3]);ctx.strokeRect(sx+2,sy+2,s-4,s-4);ctx.restore()}
function drawHud(){const my=state.match.players.find(p=>p.id===myId)||state.match.players[0],r=my?.resources||{};const obj=state.match.objective;const progress=my?.objectiveProgress||0;$('#hud').innerHTML=`<div class="topbar"><div class="logoMini"><span>◈</span><b>TIDELANDS</b></div><div class="resources"><div>🪙 <b>${fmt(r.credits)}</b><small>+35/m</small></div><div>▰ <b>${fmt(r.materials)}</b><small>+18/m</small></div><div>▣ <b>${fmt(r.industry)}</b><small>+3/m</small></div><div>⚡ <b>${fmt(r.energy)}</b><small>+8/m</small></div><div>👥 <b>${fmt(r.population)}</b><small>+2/m</small></div></div><div class="topActions"><span>◷ ${state.tick||0}</span><button data-ui="help">?</button><button data-ui="settings">⚙</button></div></div>
 <aside class="leftPanel"><div class="playerCard"><div class="crest">♛</div><div><b>${esc(my?.name||'Player')}</b><small>${my?.team||'Blue'} • ${my?.score||0} SCORE</small></div></div><button class="sideBtn active" data-ui="economy">♜ <span>Economy</span></button><button class="sideBtn" data-ui="buildings">▦ <span>Buildings</span></button><button class="sideBtn" data-ui="units">♟ <span>Units</span></button><button class="sideBtn" data-ui="research">⌬ <span>Research</span></button><button class="sideBtn" data-ui="diplomacy">♢ <span>Diplomacy</span></button></aside>
 <aside class="rightPanel"><div class="tabs"><button class="tab active">${tr('objective')}</button><button class="tab">Diplomacy</button><button class="tab">Events</button></div><div class="objectiveBig"><div class="objIcon">★</div><div><b>${esc(obj.name)}</b><small>${esc(obj.desc)}</small></div></div><div class="meter"><i style="width:${progress}%"></i></div><div class="event"><b>Turn ${Math.floor((state.tick||0)/60)+1}</b><span>${progress}% objective progress</span></div><div class="event"><b>Territory</b><span>${mcount(my?.id)} tiles controlled</span></div>${selected?`<div class="selection"><b>${selected.city?esc(selected.city.name):selected.terrain.toUpperCase()}</b><span>${selected.owner===my?.id?'YOUR TERRITORY':selected.owner?'CONTROLLED':'UNCLAIMED'} • ${selected.x}, ${selected.y}</span></div>`:''}</aside>`;
 $('#hud').querySelectorAll('[data-ui]').forEach(b=>b.onclick=()=>openGamePanel(b.dataset.ui));
}
function mcount(id){return state.match.map.tiles.filter(t=>t.owner===id).length}
function fmt(n){return Math.floor(n||0).toLocaleString()}
const buildDefs=[['city','City Center','2000'],['farm','Farm','500'],['mine','Mine','800'],['factory','Factory','1200'],['power','Power Plant','1000'],['warehouse','Warehouse','700'],['port','Port','1500'],['airport','Airport','2000'],['radar','Radar','1500'],['defense','Defense','1300']];
function buildBar(){const bar=$('#buildbar');bar.innerHTML=`<div class="cityInfo"><b>Oceanview</b><small>Level 1 • Capital</small></div>${buildDefs.map(([id,n,c])=>`<button class="build ${buildMode===id?'selected':''}" data-build="${id}"><span class="buildIcon">${iconFor(id)}</span><b>${n}</b><small>🪙 ${c}</small></button>`).join('')}<button class="build cancelBuild" id="cancelBuild">✕<b>${tr('cancel')}</b></button>`;bar.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{buildMode=buildMode===b.dataset.build?null:b.dataset.build;buildBar();render()});$('#cancelBuild').onclick=()=>{buildMode=null;buildBar();render()}}
function iconFor(id){return ({city:'▥',farm:'⌁',mine:'◆',factory:'▦',power:'ϟ',warehouse:'▤',port:'⚓',airport:'✈',radar:'◉',defense:'⬢'})[id]||'◆'}
function openGamePanel(kind){const my=state.match.players.find(p=>p.id===myId)||state.match.players[0];let title=kind[0].toUpperCase()+kind.slice(1),body='';if(kind==='economy')body=`<p>Credits <b>${fmt(my.resources.credits)}</b></p><p>Materials <b>${fmt(my.resources.materials)}</b></p><p>Energy <b>${fmt(my.resources.energy)}</b></p><p>Population <b>${fmt(my.resources.population)}</b></p><p>Industry <b>${fmt(my.resources.industry)}</b></p>`;else if(kind==='buildings')body=`<p>Buildings: <b>${my.buildings.length}</b></p><div class="miniList">${my.buildings.map(b=>`<span>${iconFor(b.type)} ${b.type}</span>`).join('')||'<small>No buildings yet — select a building below and tap your territory.</small>'}</div>`;else if(kind==='units')body='<p>Units are coming next; the current map is ready for unit placement and selection.</p>';else if(kind==='research')body='<p>Research framework is reserved for the next simulation layer.</p>';else if(kind==='diplomacy')body=`<p>Players</p>${state.match.players.map(p=>`<div class="room"><span>${esc(p.name)}</span><span>${p.team}</span></div>`).join('')}`;else body='<p>Use drag/tap on the map and the build bar to interact.</p>';openPanel(`<h2>${title}</h2>${body}<button class="back" id="closeGamePanel">${tr('back')}</button>`);$('#closeGamePanel').onclick=closePanel}
function applyDelta(m){if(!state?.match)return;const p=state.match.players.find(x=>x.id===m.playerId);if(p&&m.resources)p.resources=m.resources;const a=m.action;if(a?.type==='tile_claimed'){const t=state.match.map.tiles.find(t=>t.x===a.x&&t.y===a.y);if(t)t.owner=m.playerId}if(a?.type==='building_added'&&p){p.buildings=p.buildings||[];if(!p.buildings.some(b=>b.id===a.building.id))p.buildings.push(a.building)}render()}
function addChat(s){const el=$('#chatLog');if(!el)return;el.innerHTML+=`<div>${s}</div>`;el.scrollTop=el.scrollHeight}
function toast(s){addChat(`<span class="bad">${esc(s)}</span>`)}
function clickTile(t){selected=t;if(buildMode){if(t.owner===myId&&t.terrain!=='water')send({type:'build',building:buildMode,x:t.x,y:t.y});else toast('BUILD REJECTED — select your territory');buildMode=null;buildBar();return}if(t.owner===null&&t.terrain!=='water'){send({type:'claim',x:t.x,y:t.y})}render()}
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y};lastPointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{hover=tileAt(e.clientX,e.clientY);if(drag){camera.x=drag.cx-(e.clientX-drag.x)/camera.zoom;camera.y=drag.cy-(e.clientY-drag.y)/camera.zoom;render()}});
canvas.addEventListener('pointerup',e=>{if(!drag)return;const moved=Math.hypot(e.clientX-drag.x,e.clientY-drag.y);if(moved<7){hover=tileAt(e.clientX,e.clientY);if(hover)clickTile(hover)}drag=null});
canvas.addEventListener('wheel',e=>{e.preventDefault();const before=screenToWorld(e.clientX,e.clientY);camera.zoom=Math.max(.55,Math.min(1.75,camera.zoom*(e.deltaY<0?1.09:.92)));const after=screenToWorld(e.clientX,e.clientY);camera.x+=before[0]-after[0];camera.y+=before[1]-after[1];render()},{passive:false});
addEventListener('resize',()=>{resize();render()});
$('#chat form').onsubmit=e=>{e.preventDefault();const v=$('#chatInput').value.trim();if(v)send({type:'chat',text:v});$('#chatInput').value=''};
bindMenu();connect();void Phaser;
